### PR TITLE
removed debugging code

### PR DESCRIPTION
**Pull request by nr0cinu**
There was a `browser()` statement in the code.

### CODE REVIEW

**Comment by Aciole-David** [comment]
> There was a `browser()` statement in the code.

Thanks! I just ignored the debug browser here...
Are you from Xia's lab or, like me, just a guy trying to use their code?
I posted an issue about alpha diversity and it would be great if more people come to help fixing things, since the devs don't show up

**Comment by nr0cinu** [comment]
Hi @Aciole-David!

>  Are you from Xia's lab or, like me, just a guy trying to use their code?

Not from Xia’s lab. I’m from the JMF. We are just using MicrobiomeAnalyst and MicrobiomeAnalystR for some of our projects.

>  I posted an issue about alpha diversity and it would be great if more people come to help fixing things, since the devs don't show up

If you want to start a fork, I’m happy to help out when I find errors :)

Thanks,
Bela

**Comment by Aciole-David** [comment]
> Hi @Aciole-David!
> 
> > Are you from Xia's lab or, like me, just a guy trying to use their code?
> 
> Not from Xia’s lab. I’m from the JMF. We are just using MicrobiomeAnalyst and MicrobiomeAnalystR for some of our projects.
> 
> > I posted an issue about alpha diversity and it would be great if more people come to help fixing things, since the devs don't show up
> 
> If you want to start a fork, I’m happy to help out when I find errors :)
> 
> Thanks,
> Bela

Great! Thank you

**Comment by nr0cinu** [comment]
Fixed in 0a8d81afeb3b637122c97c2d17146a44fa978c4f. Thanks

**Pull request closed without merging**
